title: Pie Docs
description: Serving up delicious documentation one slice at a time

lang: en-US
# branch: master
branch: piedocs

# Pages to include in header navigation
nav_pages:
  - index.html
  - about.md

# Disqus login information, for comments
disqus:
  shortname: DISQUS_USERNAME

# Google Analytics tracking id
ga_username: UA-xxxxxxxx-x

# Links to include on the contact page
contact_links:
#  - name: Twitter
#    url: https://twitter.com/
#    icon: twitter
#  - name: Facebook
#    url: https://facebook.com/
#    icon: facebook

# Front matter defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      comments: false
      hero: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page
      comments: false
      hero: true

plugins:
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-github-metadata
  - jekyll-feed
  - jekyll-remote-theme
 
exclude:
  - vendor/bundle
  - node_modules

remote_theme: benbalter/retlab
